-- Run this in the Supabase SQL editor before using the app.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null,
  email text not null unique,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;

drop policy if exists "profiles can read own row" on public.profiles;
create policy "profiles can read own row"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "profiles can insert own row" on public.profiles;
create policy "profiles can insert own row"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles can update own row" on public.profiles;
create policy "profiles can update own row"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, email, role, created_at, updated_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    new.email,
    case when lower(new.email) = 'vamsiallam77@gmail.com' then 'admin' else 'user' end,
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (id) do update set
    username = excluded.username,
    email = excluded.email,
    role = excluded.role,
    updated_at = excluded.updated_at;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create table if not exists public.player_lookups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  player_tag text not null,
  player_name text,
  player_data jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, player_tag)
);

alter table public.player_lookups enable row level security;

drop policy if exists "player_lookups select own" on public.player_lookups;
create policy "player_lookups select own"
on public.player_lookups
for select
using (auth.uid() = user_id);

drop policy if exists "player_lookups insert own" on public.player_lookups;
create policy "player_lookups insert own"
on public.player_lookups
for insert
with check (auth.uid() = user_id);

drop policy if exists "player_lookups update own" on public.player_lookups;
create policy "player_lookups update own"
on public.player_lookups
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "player_lookups delete own" on public.player_lookups;
create policy "player_lookups delete own"
on public.player_lookups
for delete
using (auth.uid() = user_id);

drop trigger if exists player_lookups_set_updated_at on public.player_lookups;
create trigger player_lookups_set_updated_at
before update on public.player_lookups
for each row
execute function public.set_updated_at();
